name: Build and Docker Push

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo
  REGISTRY: ghcr.io
  IMAGE_NAME: asadarafat/bngblaster

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Set Docker version tag
        id: vars
        run: |
          echo "ℹ️ Fetching the latest valid tag from GitHub API..."
          TAG_NAME=$(curl -s https://api.github.com/repos/asadarafat/bngblaster/tags | jq -r '[.[] | select(.name != "delete")][0].name')

          if [[ -z "$TAG_NAME" || "$TAG_NAME" == "null" ]]; then
            echo "❌ No valid tag found. Exiting."
            exit 1
          fi

          echo "✅ Using tag: $TAG_NAME"
          echo "version=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Generate Dockerfile dynamically
        run: |
          TAG_NAME="${{ steps.vars.outputs.version }}"
          cat <<EOF > Dockerfile
          FROM ubuntu:latest

          USER root:root
          RUN echo 'root:admin' | chpasswd

          WORKDIR ./opt/bngblaster

          RUN apt-get update && \
              apt-get install -y sudo iproute2 iputils-ping openssh-server iproute2 iputils-ping vim wget && \
              apt-get clean && rm -rf /var/lib/apt/lists/*

          # Config SSH
          RUN echo "HostKeyAlgorithms ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519" >> /etc/ssh/ssh_config    
          RUN echo "KexAlgorithms diffie-hellman-group1-sha1,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1" >> /etc/ssh/ssh_config    
          RUN service ssh restart

          # Create admin user with sudo access
          RUN useradd -m -s /bin/bash admin && \
              echo "admin:admin" | chpasswd && \
              usermod -aG sudo admin && \
              echo "admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

          # Get and install BngBlaster
          RUN wget -O /tmp/bngblaster-$TAG_NAME-ubuntu-24.04_amd64.deb https://github.com/rtbrick/bngblaster/releases/download/$TAG_NAME/bngblaster-$TAG_NAME-ubuntu-24.04_amd64.deb
          RUN apt-get install -y /tmp/bngblaster-$TAG_NAME-ubuntu-22.04_amd64.deb

          ENTRYPOINT bash
          EOF

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.vars.outputs.version }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
